routes/web.php
  Route::post('getTransByDateRange', 'PageController@getTransByDateRange')->name('getTransByDateRange');
  Route::post('moveToExcel', 'PageController@moveToExcel')->name('moveToExcel');
  
  // Admin
  Route::get('admin', 'PageController@viewAdmin')->name('admin');
  Route::get('findmenu_options', 'PageController@findmenu_options')->name('findmenu_options');
  Route::post('add_user_menu', 'PageController@add_user_menu')->name('add_user_menu');
  Route::get('brandupdate', 'PageController@brandupdate')->name('brandupdate');
  Route::post('brandupdate', 'PageController@brandupdate')->name('brandupdate');
//Babar works 
  Route::get('/booking', 'BookingController@booking')->name('booking');
  // User Profile
  Route::get('/profile', 'UserController@showProfile')->name('profile');
  Route::post('/profile', 'UserController@updatePic')->name('updatePic');
  Route::post('/updateUser', 'UserController@updateUser')->name('updateUser');

  Route::get('/upcoming_services', 'PageController@upcomingServices')->name('upcomingServices');
  

  //My Posts
  Route::get('/my_posts', 'PageController@myPosts')->name('myPosts');
  Route::get('saved_posts', 'PageController@getSavePost')->name('getSavePost');
  //Coupon
  Route::get('/coupon', 'CouponController@coupons')->name('coupons'); 
  Route::get('/coupon/action', 'CouponController@action')->name('coupon.action');
  Route::get('/coupon/create', 'CouponController@create')->name('coupon.create');
  Route::post('/coupon/create', 'CouponController@store')->name('coupon.store'); 
  Route::get('/coupon/{id}/edit', 'CouponController@editCoupon')->name('coupon.edit'); 
  Route::post('/coupon/{id}/update', 'CouponController@updateCoupon')->name('coupon.update');  
  Route::get('/coupon/{id}/delete', 'CouponController@deleteCoupon')->name('coupon.delete');


  // All Order details
  //Show All Orders
  Route::get('/order', 'OrderController@index')->name('order');
  //Buyer order from single buyer post
  Route::PUT('/buyerOrder/{id}', 'OrderController@buyerOrder')->name('buyerOrder');
  Route::get('/buyerShow/{id}', 'OrderController@buyerShow')->name('buyerShow');
  Route::get('/buyerSingle/{id}', 'OrderController@buyerSingle')->name('buyerSingle');
  Route::PUT('/buyerStatus/{id}', 'OrderController@buyerStatus')->name('buyerStatus');
  //Seller order from single seller post
  Route::PUT('/sellerOrder/{id}', 'OrderController@sellerOrder')->name('sellerOrder');
  // Route::get('/sellerShow/{id}', 'OrderController@sellerShow')->name('sellerShow');
  Route::get('/sellerSingle/{id}', 'OrderController@sellerSingle')->name('sellerSingle');
  Route::PUT('/sellerStatus/{id}', 'OrderController@sellerStatus')->name('sellerStatus');
  //Posts (buyer, seller, article)
  Route::resource('/buyer', 'BuyerController');
  Route::resource('/seller', 'SellerController');
  Route::resource('/article', 'ArticleController');
  //email
  Route::resource('/email', 'EmailController');


});
//Waqas Changes
Route::middleware(['auth'])->group(function () {
    Route::post('user-access-ajax', 'PageController@userAccessAjax')->name('UserAccessAjax');
    Route::post('edit-or-create-new-user', 'PageController@saveExistingUser')->name('saveExistingUser');
    Route::post('create-user/{flag}', 'PageController@CreateUserWith')->name('CreateUserWith');
    Route::post('delete-user', 'PageController@deleteProfile')->name('deleteProfile');

});

//Routes for advertisement

Route::get('/advertisement', 'AdvertisementController@index')->name('AdvertisementPage');

Route::post('/AdvertisementAction', 'AdvertisementController@action')->name('AdvertisementAction');
Route::get('/advertisement/show', 'AdvertisementController@viewAds')->name('AdvertisementShow');
Route::post('deleteAdd', 'AdvertisementController@deleteAdd')->name('deleteAdd');
Route::post('getAdsData', 'AdvertisementController@getAdsData')->name('getAdsData');
Route::post('addProfession', 'PageController@addProfession')->name('addProfession');
Route::post('getProfession', 'PageController@getProfession')->name('getProfession');
Route::post('updateProfession', 'PageController@updateProfession')->name('updateProfession');
Route::post('deleteProfession', 'PageController@deleteProfession')->name('deleteProfession');
Route::post('getProfessionOfType', 'PageController@getProfessionOfType')->name('getProfessionOfType');
Route::post('submitMembershipForm', 'PageController@submitMembershipForm')->name('submitMembershipForm');


Route::get('foo', function () {
  return 'Hello World';
});

/////////////////// ///////////////////////////////////
  ///////////////////////// Abdul Rehman Code ///////////////////////

  Route::get('/faqsetup', 'FaqController@faqs')->name('faqs');
  Route::get('/faq', 'FaqController@faquser')->name('faquser');
  Route::post('/faqsetup/create', 'FaqController@store')->name('faq.store'); 
  Route::get('/faqsetup/{id}/delete', 'FaqController@deleteFaq')->name('faq.delete');
  Route::get('/faqsetup/{id}/edit', 'FaqController@editFaq')->name('faq.edit'); 
  Route::post('/faqsetup/{id}/update', 'FaqController@updateFaq')->name('faq.update');


  //Exam
  
  Route::get('/examsetup', 'ExamController@exams')->name('exams');
  Route::get('/exam', 'ExamController@examuser')->name('examuser');
  Route::post('/examsetup/create', 'ExamController@store')->name('exam.store'); 
  Route::get('/examsetup/{id}/delete', 'ExamController@deleteExam')->name('exam.delete');
  Route::get('/examsetup/{id}/edit', 'ExamController@editExam')->name('exam.edit'); 
  Route::post('/examsetup/{id}/update', 'ExamController@updateExam')->name('exam.update');
    Route::post('/examsetup/check', 'ExamController@checkExam')->name('exam.check');


  //Train
  Route::get('/trainsetup', 'TrainController@trains')->name('trains');
  Route::get('/train', 'TrainController@trainuser')->name('trainuser');
  Route::post('/trainsetup/create', 'TrainController@store')->name('train.store'); 
  Route::get('/trainsetup/{id}/delete', 'TrainController@deleteTrain')->name('train.delete');
  Route::get('/trainsetup/{id}/edit', 'TrainController@editTrain')->name('train.edit'); 
  Route::post('/trainsetup/{id}/update', 'TrainController@updateTrain')->name('train.update');

////////////////// Home Page Setup /////////////////////

Route::get('/homepage-setup', 'UserController@homepageSetup');
Route::post('/sethomepage', 'UserController@setHomepageSetup');


//chat ........
Route::get('/chatdashboard', 'ChatDashboardController@index')->name('chatdashboard');
Route::get('/privateChat/{chatRoomId}', 'PrivateChatController@rtnChatBox')->name('privateChat');
Route::post('/send/{id}', 'PrivateChatController@store');
Route::post('/geturl', 'PrivateChatController@geturl');
Route::post('/timeformate', 'PrivateChatController@timeformate');
Route::post('/setuserlocalutc', 'PrivateChatController@setuserlocalutc');
Route::get('/getlogedinusertime', 'PrivateChatController@getlogedinusertime')->name('getlogedinusertime');

Route::post('/getOldMessage', 'ChatController@getOldMessage');
Route::post('/chatSpam/{id}', 'ChatController@spam');
Route::post('/chatReport/{id}', 'ChatController@report');
Route::get('/chatsearch', 'searchController@search')->name('chatsearch');
Route::get('/defaullevelsearch', 'searchController@defaullevelsearch')->name('defaullevelsearch');
Route::get('/levelsearch', 'searchController@levelsearch')->name('levelsearch');
Route::get('/unreadsearch', 'searchController@unreadsearch')->name('unreadsearch');
Route::get('/indeviduallevelsearch', 'searchController@indeviduallevelsearch')->name('indeviduallevelsearch');

Route::post('/setonline', 'ChatController@setonline');
Route::post('/setoffline', 'ChatController@setoffline');
Route::post('/getallOnlineUser', 'ChatController@getallOnlineUser');
Route::post('/readwrite', 'ChatController@readwrite');

Route::get('/levelset', 'LevelController@index')->name('levelset');
Route::get('/getOldLevel', 'LevelController@getOldLevel');
Route::post('/addcustomlevel', 'LevelController@custom');
Route::get('/leveldel/{id}', 'LevelController@delete')->name('leveldel');
Route::get('/starchat/{id}', 'LevelController@starchat')->name('starchat');
Route::get('/delallchat/{id}', 'LevelController@delallchat');
Route::get('/getmessagepopup', 'messagepopController@index')->name('messagepop');
Route::get('/getmessagepopupcross', 'messagepopController@getmessagepopupcross');

Route::get('/gmtime', 'PrivateChatController@test');
Route::get('/testtt', 'searchController@test');
Route::get('/sendemailforunread', 'PrivateChatController@sendemailforunread');
Route::post('/sendmail', 'PrivateChatController@sendmail');

//end of chat..........
Route::post('getAndMoveVerifyDetails', 'PageController@getAndMoveVerifyDetails')->name('getAndMoveVerifyDetails');
Route::get('getMemberDetailsUsingEmail', 'PageController@getMemberDetailsUsingEmail')->name('getMemberDetailsUsingEmail');
//////////////////////// Blog /////////////////////////////

Route::get('/blog', 'BlogController@index')->name('blog');
Route::get('/my-blog', 'BlogController@myBlog');
Route::get('/add-blog', 'BlogController@addBlog');
Route::post('/blog/store', 'BlogController@storeBlog');
Route::get('/public-blog', 'BlogController@publicBlog');
Route::get('/blod-details/{ids}', 'BlogController@blogDetails');
Route::post('/add_comment/{post_id}/{user_id}','BlogController@addComment');
Route::get('/delete_post/{post_id}', 'BlogController@deletePost');
Route::get('/delete_comment/{comment_id}', 'BlogController@deleteComment');
Route::get('/visitors-details/{ids}', 'BlogController@visitorDetails');


/////////////////////// Sakib changes ///////////////////

Route::resource('/events', 'EventsController');
Route::resource('/eventM', 'EventModalController');
Route::get('/search', 'EventsController@search')->name('search');
Route::get('/going-to-event/{user_id}/{owner_id}/{event_id}','EventsController@goingToEvent');
Route::get('/not-going-to-event/{user_id}/{owner_id}/{event_id}','EventsController@notGoingToEvent');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
  public function user()
  {
      return $this->belongsTo(User::class);
  }
}

resources/views/pages/events/index.blade.php
@extends('layouts.app')
@section('custom-styles')
<link rel="stylesheet" href="{{ asset('css/tempusdominus-bootstrap-4.css') }}">
{{-- <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/2.3.2/css/bootstrap.min.css"> --}}
<link rel="stylesheet" href="{{asset('css/style.css')}}">
<link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
@endsection
@section('content')
<section id="section-sidebar-left">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="form-row">
          <div class="form-group col-md-10 m-auto text-center">
            <img id="user_avatar_img" src="{{ asset('/uploads/avatars/' . Auth::user()->avatar) }}"
            style="width:100px; height:100px; border-radius:50%;">
          </div>
          <form id="search-user" action="{{ URL('/search') }}" method="GET" role="search">
            <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
            <div class="form-group col-md-10 m-auto">
              @if (session('status'))
                  <div class="alert alert-success">
                      {{ session('status') }}
                  </div>
              @endif
              <div class="input-group" style="width: 297px;margin-left: -56px;">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-user"></i></div>
                </div>
                <input class="form-control" id="find_email" name="find_email" type="search" placeholder="Search" aria-label="Search" value="{{ old('find_email') }}">
                <div class="input-group-append">
                  <button class="btn btn-secondary search_user" type="submit" id="button-addon2">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
        <br>
           
                <div class="row">
                    <div class="col-md-8 ">
                        <div class="example1" style="margin:0 auto;margin-left: -25px !important;"></div>
                    </div>
                </div>
      
        <br>
        <div class="col-md-12" style="border:1px solid gray;padding-bottom:5px;padding-top:20px;padding-left:0px;padding-right:0px;width:295px !important;margin-left:-20px;max-width:295px">
         
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-bottom: 10px;">
                  <ul class="ul-schedule-list">
                    <li class="" >
                      <a href=""><i class="fas fa-square"></i> &nbsp; All Events</a>
                    </li>
                  </ul>
              </div>
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                      <li class="" style="padding-bottom: 10px;">
                        <a href=""><i class="fa fa-circle" style="color: pink;" aria-hidden="true"></i> &nbsp; Club Events</a>
                      </li>
                      <li class="">
                          <a href=""><i class="fa fa-circle" style="color: blue;" aria-hidden="true"></i> &nbsp; Club Member Events</a>
                        </li>
                    </ul>
              </div>

              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                      <li class="" style="padding-bottom: 10px;" >
                        <a href=""><i class="fa fa-circle" style="color: purple;" aria-hidden="true"></i> &nbsp;Events Opened by Me</a>
                      </li>
                      <li class="">
                          <a href=""><i class="fa fa-circle" style="color: yellow;" aria-hidden="true"></i> &nbsp;Waiting for my approval</a>
                        </li>
                    </ul>
              </div>
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                      <li class="" style="padding-bottom: 10px;">
                        <a href=""><i class="fa fa-circle" style="color: red;" aria-hidden="true"></i> &nbsp;I am waiting for approval</a>
                      </li>
                      <li class="" >
                          <a href=""><i class="fa fa-circle" style="color: green;" aria-hidden="true"></i> &nbsp; Event Booked By Me</a>
                        </li>
                    </ul>
              </div>
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 15px;padding-bottom: 15px;">
                  <ul class="ul-schedule-list">
                    <li class="" >
                        <a href="{{ route('events.create') }}">  <i class="fas fa-plus"></i> &nbsp Add new Event</a>
                    </li>
                  </ul>
              </div>
              <div class="ul-schedule-list" style="padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                    <li class="" >
                      <a href=""><i class="fas fa-certificate"></i> &nbsp; My Availability</a>
                    </li>
                  </ul>
              </div>
                
                {{-- <h5 class="mt-4">Schedule</h5> --}}
                {{-- <ul class="ul-schedule-list">
                  <li class="li-schedule-list mylist" >
                    <a href="">Waiting for approval</a>
                  </li>
                  
                  <li class="li-schedule-list">
                    <a href="">Asked my schedule</a>
                  </li>
                  <li class="li-schedule-list">
                    <a href="">Booked schedule</a>
                  </li>
                  <li class="li-schedule-list">
                    <a href="{{ route('events.create') }}">Add a schedule</a>
                  </li>
                  <li class="li-schedule-list">
                    <a href="">Ask a schedule</a>
                  </li>
                </ul>
                {{-- <h5 class="mt-4">Events</h5> --}}
                {{-- <ul class="ul-event-list">
                  <li class="li-event-list">
                    <a href="">Club events</a>
                  </li>
                  <li class="li-event-list">
                    <a href="">Joining events</a>
                  </li>
                  <li class="li-event-list">
                    <a href="">My open events</a>
                  </li>
                  <li class="li-event-list">
                    <a href="">Add New event</a>
                  </li>
                </ul>  --}}
            
            
        </div>
      </div>
      
      <div class="col-md-9">
        <div class="row">
          
          @foreach ($events as $event)
          <div class="col-sm-4">
            <div class="card">
              <div class="card-img-top">
                <a href="{{ route('events.show', $event->id) }}">
                  <img src="{{ asset('uploads/event/' . $event->event_featured_image) }}" style="width: 100%;">
                </a>
              </div>
              <div class="card-body">
                <div class="row">
                    <div class="col-md-12 p-0 pl-2">

                      
                     <h3>{{ $event->event_title }}</h3>

                    </div>
                </div>  
                <div class="row">
                  <div class="col-md-4 p-0 pl-2">
                    <div class="h5 text-danger "><strong>{{ date('M', strtotime($event->event_date)) }}</strong></div>
                    <div class="h5 mt-0">{{ date('j', strtotime($event->event_date)) }}</div>
                  </div>
                  <div class="col-md-6 p-0 pl-2">

                  <div class="text-muted"><strong><small>{{ ($event->event_start_time) }} - {{ ($event->event_end_time) }}</small></strong></div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-8 ">
                      @if(empty($event->event_ticket_price))
                      <div class="text-center"><i class="fas fa-ticket-alt"></i>
                        <strong>$0</strong>
                      </div>
                      @else
                      <div class="text-center" style="margin-left:-20px"><i class="fas fa-ticket-alt"></i>
                        <strong>${{ ($event->event_ticket_price) }}</strong> &nbsp; <strong><small>No refund</small></strong>
                      </div>
                      @endif
                      
                    </div>
                  <div class="col-md-4 ">

                    <input type="checkbox" class="custom-control-input" id="event_is_online" name="event_is_online" disabled >
                      <label class="custom-control-label" for="event_is_online">Online</label><br>
                  </div>
                </div>
                <div class="row" style="margin-top:10px">
                  <div class="col-md-4">
                    <div class="text-muted">
                        {{ substr(strip_tags($event->event_city), 0, 5) }}
                      
                      </div>
                  </div>
                  <div class="col-md-4">
                      <div class="text-muted">
                      
                          {{ substr(strip_tags($event->event_country), 0, 3) }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="text-muted">
                           
                            {{ substr(strip_tags($event->event_phone), 0, 3) }}
                          </div>
                      </div>
                </div>
                <div class="row" style="margin-top:10px">  
                  <div class="col-md-6 ">
                    {{-- <h5 class="card-title mb-1">{{ $event->event_title }}</h5> --}}

                    {{-- <div class="text-muted"><strong><small>{{ ($event->event_start_time) }} - {{ ($event->event_end_time) }}</small></strong></div> --}}
                    <div class="text-muted">
                      @if(empty($event->interested_in_event))
                        0 interested
                      @else
                        {{ ($event->interested_in_event) }} interested
                      @endif
                    </div>
                  </div>  
                    <div class="col-md-4 p-0">
                        <div class="text-muted">
                      @if(empty($event->going_in_event))
                      0 going
                   @else
                     {{ ($event->going_in_event) }} going
                   @endif
                        </div>
                    </div>
                    
                    {{-- <div class="text-muted">
                      {{ substr(strip_tags($event->event_city), 0, 5) }},
                      {{ substr(strip_tags($event->event_country), 0, 3) }}
                    </div> --}}
                
                  
                </div>
              </div>
              

              <div class="col-md-12" style="margin-bottom:5px">
                  <hr id="event_view_border">
                  <button class="btn btn-default">
                    <a href="#"><i class="fas fa-share-square fa-1x"></i></a>
                  </button>
                  <button class="btn btn-default">
                    <a href="#"><i class="far fa-star fa-1x"></i></a>
                  </button>

                  	<?php $flag=false ?>
                    @foreach ($eventVisitors as $eventVisitor)
              

                      @if($eventVisitor->user_id == Auth::user()->id)

                      <?php $flag=true; ?>
                        <a class="btn btn-default" type="button"  name="event_not_going" style="float:right;"
                        href="/not-going-to-event/{{Auth::user()->id}}/{{$event->user_id}}/{{$event->id}}"> <i class="fa fa-times fa-1x"></i> going 
                        </a>
                        
                      {{-- @else
                      
                        <a class="btn btn-default" type="button"  name="event_not_going" style="float:right;"
                          href="/not-going-to-event/{{Auth::user()->id}}/{{$event->user_id}}/{{$event->id}}"> <i class="fa fa-times fa-1x"></i> going 
                        </a> --}}

                      @endif

                    @endforeach

                    <?php if($flag == false){ ?>
                    
                      <a class="btn btn-default" type="button"  name="event_not_going" style="float:right;"
                          href="/going-to-event/{{Auth::user()->id}}/{{$event->user_id}}/{{$event->id}}"> <i class="fa fa-check fa-1x"></i> going 
                        </a> 
                      
                    <?php } ?>
                
                </div>
            </div>
          </div>
          @endforeach
      </div>
    </div>
  </div>
  <div class="text-center">
    {!! $events->links(); !!}
  </div>
</div>
</section>
@endsection

@section('extra-JS')
<script src="{{ asset('js/jquery.supercal.js')}}"></script> 
<script type="text/javascript">
	$('.example1').supercal({
				transition: 'carousel-vertical'
			});
    $(function () {
        $('#datetimepicker13').datetimepicker({
           
        });
    });
</script>
@endsection